"""Build the LOV QUEST sprite atlas + logo (run from anywhere: `python components/lov-quest/forge/forge.py`).

Requires Python 3.9+, numpy and Pillow. Writes:
  public/lov-quest/atlas.png        all game sprites (runner variants, props, fx)
  public/lov-quest/logo.png         pixel wordmark (1x)
  components/lov-quest/atlas.ts     frame rectangles
"""
import os
from pathlib import Path
import numpy as np
from pal import *  # noqa
import props as P
import runner as R
import logo as L

ROOT = str(Path(__file__).resolve().parents[3])
PUB = os.path.join(ROOT, "public/lov-quest")
COMP = os.path.join(ROOT, "components/lov-quest")
os.makedirs(PUB, exist_ok=True)
os.makedirs(COMP, exist_ok=True)

sprites = {}  # name -> array

VARIANTS = {
    # class id -> (torso variant, head)
    "tee": ("tee", "cap"),
    "singlet": ("singlet", "cap"),
    "jacket": ("jacket", "cap"),
    "lamp": ("tee", "lamp"),
    "hair": ("tee", "hair"),
}
for vid, (torso, head) in VARIANTS.items():
    for i in range(8):
        sprites[f"{vid}_run{i}"] = R.run_frame(i, torso, head)[0]
    sprites[f"{vid}_jump"] = R.jump_frame(torso, head)[0]
    sprites[f"{vid}_fall"] = R.fall_frame(torso, head)[0]
    sprites[f"{vid}_hurt"] = R.hurt_frame(torso)[0]
    sprites[f"{vid}_idle"] = R.idle_frame(torso, head)[0]
    sprites[f"{vid}_cheer"] = R.cheer_frame(torso, head)[0]

sprites["rock_s"] = outline(P.ROCK_S)
sprites["rock_l"] = outline(P.ROCK_L)
sprites["bush"] = outline(P.BUSH)
sprites["goat0"] = outline(P.GOAT_A)
sprites["goat1"] = outline(P.GOAT_B)
sprites["gel"] = outline(P.GEL)
sprites["heart"] = outline(P.HEART)
sprites["heart_empty"] = outline(P.HEART_EMPTY)
sprites["palm"] = outline(P.PALM)
sprites["boat"] = outline(P.BOAT)
sprites["flag0"] = outline(P.FLAG_A)
sprites["flag1"] = outline(P.FLAG_B)
for i, d in enumerate(P.DUST):
    sprites[f"dust{i}"] = d
for i, s in enumerate(P.SPARK):
    sprites[f"spark{i}"] = s

# --- pack (simple shelf packer) ---
ATLAS_W = 512
x = y = 0
shelf_h = 0
rects = {}
order = sorted(sprites.items(), key=lambda kv: -kv[1].shape[0])
for name, a in order:
    h, w = a.shape
    if x + w > ATLAS_W:
        x = 0
        y += shelf_h + 1
        shelf_h = 0
    rects[name] = (x, y, w, h)
    x += w + 1
    shelf_h = max(shelf_h, h)
ATLAS_H = y + shelf_h
atlas = np.full((ATLAS_H, ATLAS_W), T, dtype=np.int16)
for name, (rx, ry, rw, rh) in rects.items():
    blit(atlas, sprites[name], rx, ry)
to_rgba(atlas).save(os.path.join(PUB, "atlas.png"), optimize=True)

lg = L.build()
to_rgba(lg).save(os.path.join(PUB, "logo.png"), optimize=True)

lines = [
    "// GENERATED by components/lov-quest/forge/forge.py. Frame rects in /lov-quest/atlas.png.",
    "// [x, y, w, h] in atlas pixels.",
    "export type Rect = readonly [number, number, number, number];",
    "",
    f"export const ATLAS_SIZE = [{ATLAS_W}, {ATLAS_H}] as const;",
    f"export const LOGO_SIZE = [{lg.shape[1]}, {lg.shape[0]}] as const;",
    "",
    "export const FRAMES = {",
]
for name in sorted(rects):
    rx, ry, rw, rh = rects[name]
    lines.append(f"  {name}: [{rx}, {ry}, {rw}, {rh}],")
lines.append("} as const satisfies Record<string, Rect>;")
lines.append("")
lines.append("export type FrameName = keyof typeof FRAMES;")
lines.append("")
open(os.path.join(COMP, "atlas.ts"), "w").write("\n".join(lines))
print("atlas", ATLAS_W, ATLAS_H, len(rects), "sprites; logo", lg.shape)
